global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'revenue_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['revenue_api:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: revenue_api:8000

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15672']

  - job_name: 'postgres'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['db:5432']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
