global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'revenue_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: api:8080

  - job_name: 'db'
    static_configs:
      - targets: ['db:5432']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
